Import Debian changes 2.4.43-1
apache2 (2.4.43-1) unstable; urgency=medium

  [ Timo Aaltonen ]
  * mod_ssl: Add patches to fix TLS 1.3 client cert authentication for POST
    requests (Closes: #955348)

  [ Moritz Schlarb ]
  * Fix logrotate script for multi-instance (Closes: #914606)

  [ Xavier Guimard ]
  * New upstream version 2.4.43
  * Refresh patches

diff --git a/debian/rules b/debian/rules
--- a/debian/rules
+++ b/debian/rules
@@ -8,23 +8,24 @@ DEB_BUILD_ARCH_OS    ?= $(shell dpkg-architecture -qDEB_BUILD_ARCH_OS)
 
 export DEB_BUILD_MAINT_OPTIONS=hardening=+bindnow
 include /usr/share/dpkg/buildflags.mk
+include /usr/share/dpkg/architecture.mk
+include /usr/share/dpkg/pkg-info.mk
 
 LSB_RELEASE := $(shell lsb_release -i -s)
-SERVER_VERSION := $(shell dpkg-parsechangelog | perl -ne 'print $$1 if m/Version:\s*([\d\.]+)/')
-DEBIAN_VERSION := $(shell dpkg-parsechangelog | perl -ne 'print $$1 if m/Version:\s*(.+)/')
+BUILD_DATETIME := $(shell date -u --date="`dpkg-parsechangelog -S Date`" +%FT%T)
 MODULE_DIR := /usr/lib/apache2/modules/
-API = $(shell perl -ne 'print $$1 if m/define\s+MODULE_MAGIC_NUMBER_MAJOR\s+?(.*)$$/' < include/ap_mmn.h)
+API := $(shell perl -ne 'print $$1 if m/define\s+MODULE_MAGIC_NUMBER_MAJOR\s+?(.*)$$/' < include/ap_mmn.h)
+OPENSSL := openssl1.1
 AP2_CFLAGS = -pipe $(CFLAGS)
 AP2_LDFLAGS = -Wl,--as-needed $(LDFLAGS)
-AP2_CPPFLAGS = -DPLATFORM='\"$(LSB_RELEASE)\"' $(CPPFLAGS)
+AP2_CPPFLAGS = -DPLATFORM='\"$(LSB_RELEASE)\"' -DBUILD_DATETIME='\"$(BUILD_DATETIME)\"' $(CPPFLAGS)
 AP2_LTFLAGS = --no-silent
-
 
 support/suexec-custom.c: support/suexec.c debian/patches/suexec-custom.patch
 	cp support/suexec.c support/suexec-custom.c
 	patch -p1 -i debian/patches/suexec-custom.patch
 
-prebuild-checks:
+prebuild-checks-stamp:
 	ERRS="" ;\
 	for a in $$(find debian/config-dir/ -type f) ; do \
 		t="$$a.$$$$" ;\
@@ -37,22 +38,55 @@ prebuild-checks:
 		ls -1 $$ERRS ;\
 		false ;\
 	fi
+	MD5=$$(md5sum debian/index.html 2> /dev/null |cut -d' ' -f 1) ; \
+	if ! grep -q $$MD5 debian/apache2.postrm ; then \
+		echo "ERROR: index.html's md5 is missing in postrm!" ;\
+		false ; \
+	fi
+	touch $@
 
-clean-config-vars:
-	# Clean up config_vars.mk
-	# FIXME: Maybe someone could document here why we actually need to
-	# cleanup some stuff here
-	perl ./debian/clean_config_vars '$(AP2_CFLAGS)' '$(AP2_CPPFLAGS)' '$(AP2_LDFLAGS)'
+debian/fixup_conffiles.tgz: \
+    debian/config-dir/sites-available/000-default.conf \
+    debian/config-dir/sites-available/default-ssl.conf \
+    debian/config-dir/conf-available/charset.conf \
+    debian/config-dir/conf-available/localized-error-pages.conf \
+    debian/config-dir/conf-available/other-vhosts-access-log.conf \
+    debian/config-dir/conf-available/security.conf \
+    debian/config-dir/mods-available/cern_meta.load \
+    debian/config-dir/mods-available/ident.load \
+    debian/config-dir/mods-available/imagemap.load
+	@# mtime/owner/group/mode are for reproducible build
+	tar \
+		--mtime=2000-01-01T00:00Z \
+		--owner=root:0 \
+		--group=root:0 \
+		--mode=0644 \
+		--transform 's,.*/,,' \
+		-c $^ | gzip -n > $@
+
+debian/fixup_conffiles.b64: debian/fixup_conffiles.tgz
+	base64 < $< > $@
+
+debian/apache2.preinst: debian/apache2.preinst.in debian/fixup_conffiles.b64 debian/create_preinst
+	debian/create_preinst
+
+clean-config-vars-stamp: debian/tmp/usr/share/apache2/build/config_vars.mk debian/clean_config_vars
+	# Clean up config_vars.mk so that flags that are only intended for the
+	# compilation of apache2 itself are not used by apxs for compiling
+	# modules.
+	perl ./debian/clean_config_vars '$(AP2_CFLAGS)' '$(AP2_CPPFLAGS)' '$(AP2_LDFLAGS)' '$(CXXFLAGS)'
+	touch $@
 
 %: %.in
-	sed 's#__SERVER_VERSION__#$(SERVER_VERSION)#; s#__MODULE_DIR__#$(MODULE_DIR)#; s#__API__#$(API)#;' $< > $@
+	sed 's#__SERVER_VERSION__#$(DEB_VERSION_EPOCH_UPSTREAM)#; s#__MODULE_DIR__#$(MODULE_DIR)#; s#__API__#$(API)#; s#__OPENSSL__#$(OPENSSL)#;' $< > $@
 	chmod `/usr/bin/stat -c '%a' "$<"` $@
 
-prepare-scripts: debian/a2query debian/debhelper/dh_apache2
-	(grep -s -v apache2:API debian/apache2-bin.substvars; echo apache2:API=apache2-api-$(API)) > debian/apache2-bin.substvars.new
+substvars-stamp: debian/rules include/ap_mmn.h
+	(grep -s -v apache2:API debian/apache2-bin.substvars; echo "apache2:API=apache2-api-$(API), apache2-api-$(API)-$(OPENSSL)") > debian/apache2-bin.substvars.new
 	mv debian/apache2-bin.substvars.new debian/apache2-bin.substvars
+	touch $@
 
-generate-maintainer-scripts:
+suexec-scripts-stamp: $(wildcard debian/debian/apache2-suexec.*.in)
 	set -e ; \
 	for type in custom pristine ; do \
 		for f in postinst preinst prerm links dirs lintian-overrides postrm; do \
@@ -62,22 +96,16 @@ generate-maintainer-scripts:
 			fi ;\
 		done ;\
 	done
-	set -e ; \
-	for type in worker itk prefork event ; do \
-		for f in postinst preinst prerm links dirs lintian-overrides postrm; do \
-			if [ -e debian/apache2-mpm.$$f.in ] ; then \
-				perl -pe "s{__TYPE__}{$$type}g" < debian/apache2-mpm.$$f.in > debian/apache2-mpm-$$type.$$f ;\
-				chmod `/usr/bin/stat -c '%a' "debian/apache2-mpm.$$f.in"` debian/apache2-mpm-$$type.$$f ;\
-			fi ;\
-		done ;\
-	done
-
+	touch $@
 
 clean build build-arch build-indep binary binary-arch binary-indep: %:
-	dh $@ --parallel --with autotools_dev
+	dh $@ --with systemd
 
-override_dh_auto_configure: generate-maintainer-scripts prebuild-checks support/suexec-custom.c
-	./configure --enable-layout=Debian --enable-so --with-program-name=apache2 \
+override_dh_auto_configure: configure-stamp
+configure-stamp: prebuild-checks-stamp support/suexec-custom.c
+	AWK=awk \
+	./configure --host=$(DEB_HOST_GNU_TYPE) --build=$(DEB_BUILD_GNU_TYPE) \
+		--enable-layout=Debian --enable-so --with-program-name=apache2 \
 		--enable-suexec --with-suexec-caller=www-data \
 		--with-suexec-bin=/usr/lib/apache2/suexec --with-suexec-docroot=/var/www \
 		--with-suexec-userdir=public_html --with-suexec-logfile=/var/log/apache2/suexec.log \
@@ -86,14 +114,35 @@ override_dh_auto_configure: generate-maintainer-scripts prebuild-checks support/
 		--with-pcre=yes \
 		--enable-pie \
 		--enable-mpms-shared=all \
-		--enable-mods-shared="all cgi ident authnz_fcgi" \
+		--enable-mods-shared="all brotli cgi ident authnz_fcgi imagemap cern_meta proxy_fdpass proxy_http2 bucketeer case_filter case_filter_in" \
 		--enable-mods-static="unixd logio watchdog version" \
 		CFLAGS="$(AP2_CFLAGS)" CPPFLAGS="$(AP2_CPPFLAGS)" LDFLAGS="$(AP2_LDFLAGS)" \
-		LTFLAGS="$(AP2_LTFLAGS)"
+		LTFLAGS="$(AP2_LTFLAGS)" SHELL=/bin/bash GREP=/bin/grep
+	touch $@
 
+debian/config-dir/apache2.conf: debian/config-dir/apache2.conf.in
+	@# Sanity check that the marker is actually there
+	grep -q ___MUTEX___ $<
+ifeq "$(DEB_BUILD_ARCH_OS)" "linux"
+	@# On linux, we use the default pthread mutex. Comment out
+	@# Mutex directive.
+	perl -p -e 's,___MUTEX___,#,' < $< > $@
+else
+	@# On kfreebsd/hurd, pthread mutexes are not robust. There, we need to
+	@# use fcntl and set the directory explicitly for multi-instance setups.
+	perl -p -i -e 's,___MUTEX___,,' < $< > $@
+endif
 
-override_dh_install: clean-config-vars prepare-scripts
-	dh_install --list-missing
+override_dh_install: clean-config-vars-stamp \
+		     substvars-stamp \
+		     debian/config-dir/apache2.conf \
+		     debian/a2query \
+		     debian/debhelper/dh_apache2 \
+		     debian/apache2.preinst \
+		     suexec-scripts-stamp
+	# don't install mod_ssl_openssl.h in apache2-dev
+	dh_install --list-missing -papache2-dev -Xopenssl
+	dh_install --list-missing --remaining-packages
 
 override_dh_fixperms-arch:
 	# standard suexec
@@ -105,59 +154,57 @@ override_dh_fixperms-arch:
 	dh_fixperms -a -Xusr/lib/apache2/suexec-custom -Xusr/lib/apache2/suexec-pristine
 	chown -R www-data:www-data debian/apache2/var/cache/apache2/mod_cache_disk
 	chown root:adm debian/apache2/var/log/apache2
+	chmod o-rx debian/apache2/var/log/apache2
 
 override_dh_fixperms-indep:
 	dh_fixperms -i
 
 override_dh_installinit:
-	dh_installinit --restart-after-upgrade --error-handler=true -- defaults 91 09
+	dh_installinit --error-handler=true
+	# We enable apache-htcacheclean but we don't start it, some
+	# custom postinst code will then manually either disable it or
+	# start the service
+	dh_installinit --name apache-htcacheclean --no-start
+
+override_dh_systemd_enable:
+	dh_systemd_enable -papache2 apache2.service
+	dh_systemd_enable -papache2 --name=apache2@ apache2@.service
+	dh_systemd_enable -papache2 --name=apache-htcacheclean apache-htcacheclean.service
+	dh_systemd_enable -papache2 --name=apache-htcacheclean@ apache-htcacheclean@.service
 
 override_dh_installdocs-indep:
-	# TODO: So, did anyone check convert_docs needs an update? ;)
 	perl debian/convert_docs debian/apache2-doc/usr/share/doc/apache2-doc/manual
 	dh_installdocs -i
 
 override_dh_installdocs-arch:
-	dh_installdocs --link-doc=apache2 -papache2 -papache2-dbg \
-		-papache2-mpm-worker -papache2-mpm-prefork -papache2-mpm-event \
-		-papache2-mpm-itk
-	dh_installdocs --link-doc=apache2-bin -papache2.2-bin -plibapache2-mod-proxy-html \
-	    -plibapache2-mod-macro
-	dh_installdocs --link-doc=apache2-suexec-pristine -papache2-suexec
+	dh_installdocs --link-doc=apache2 -papache2 -plibapache2-mod-md -plibapache2-mod-proxy-uwsgi
+	dh_installdocs --link-doc=apache2-dev -papache2-ssl-dev
 	dh_installdocs -a
 
+override_dh_link:
+	dh_link
+	if test -e debian/apache2-doc/usr/share/doc; then \
+		jdupes -rl debian/apache2-doc/usr/share/doc; \
+	fi
+
 override_dh_installchangelogs:
-	# Do not install changelogs for transitional packages and the -data
-	# package not to trash the disk at the installation site. Together with
-	# dh_installdocs this means that changelogs are installed in a few
-	# packages only.
-	dh_installchangelogs -Napache2-suexec -Napache2-mpm-worker \
-		-Napache2-mpm-prefork -Napache2-mpm-event -Napache2-mpm-itk \
-		-Napache2-data -Nlibapache2-mod-proxy-html -Napache2.2-bin \
-		-Nlibapache2-mod-macro
+	# Do not install changelogs the -data package not to reduce
+	# disk space usage.
+	dh_installchangelogs -Napache2-data
 
 override_dh_installman:
 	mv debian/tmp/usr/share/man/man8/suexec.8 debian/tmp/usr/share/man/man8/suexec-pristine.8
+	mv debian/tmp/usr/share/man/man1/httxt2dbm.1 debian/tmp/usr/share/man/man8/httxt2dbm.8
 	pod2man debian/debhelper/dh_apache2 > debian/manpages/dh_apache2.1
 	pod2man debian/a2query.in > debian/manpages/a2query.8
 	dh_installman
 
 override_dh_strip:
-	dh_strip --dbg-package=apache2-dbg
+	dh_strip --dbgsym-migration='apache2-dbg (<< 2.4.37-2~)'
 
 override_dh_auto_install:
 	dh_auto_install -- -j1
+	rm -f debian/tmp/usr/share/apache2/error/README
+	rm -f debian/tmp/usr/share/apache2/icons/README*
 
-override_dh_builddeb:
-	dh_builddeb -- -Zxz
-
-override_dh_auto_clean:
-	dh_auto_clean
-
-override_dh_gencontrol:
-	dh_gencontrol  -p libapache2-mod-proxy-html -- -v1:$(DEBIAN_VERSION)
-	dh_gencontrol  -p libapache2-mod-macro -- -v1:$(DEBIAN_VERSION)
-	dh_gencontrol --remaining-packages
-
-.PHONY: generate-maintainer-scripts clean-config-vars prepare-scripts prebuild-checks
 .PHONY: clean build build-arch build-indep binary binary-arch binary-indep
